### ISSUE TITLE
Add transaction page

### ISSUE THREAD

**Issue by RelativeForce** [RelativeForce/MyMoney#14]
## Task
Add a page for adding new transactions

## Acceptance criteria 
- [x] The user can input the date of a transaction
- [x] The user can input the value of the transaction
- [x] The user can input a name for the transaction
