### ISSUE TITLE
Add edit transaction page

### ISSUE THREAD

**Issue by RelativeForce** [RelativeForce/MyMoney#16]
## Task
Add a page for editing existing transactions

## Acceptance criteria 
- [x] The user can go to the specific transaction page
- [x] The user can update and information of a transaction
- [x] The user must click a submit button to save there changes
