### ISSUE TITLE
Migrate API to new Budget Model

### ISSUE THREAD

**Issue by RelativeForce** [RelativeForce/MyMoney#9]
**Background**
Currently, the API supports a budget model where each budget starts and ends within a given month. This is not possible with the budget model specified in #1 

**Task**
- [x] Update budget entity to store
  - Start date (DateTime)
  - End date (DateTime)
  - Notes (String)
- [x] Update core logic to use new model
- [x] Migrate the database to the new model

**Comment by RelativeForce** [comment]
**Closing Notes**
See PR #10 for an overview of changes. There were no UI changes
